export { default as Header } from './Header'
export { default as Hero } from './Hero'
export { default as Body } from './Body'
export { default as Story } from './Story'
export { default as Jobs } from './Jobs'
export { default as Footer } from './Footer'